# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 18:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratings', '0003_auto_20180412_1445'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('reviewer', 'rating')]),
        ),
    ]
